### ISSUE TITLE
Export (CSV and BCCvL) of Occurence x Traits + Environmental data

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-service#102]
Add to Map | Species | Use species list

If there are traits from http://lists.ala.org.au, they are intersected with occurrence records via taxa. We need to be able to export a point layer that contains (in effect) appended traits as a CSV file (with optional environmental intersections) or as is to BCCvL for trait analyses.

Need to identify if the point layer to be exported contains trait data from Lists. 

Applies to Export |  Points and Export | to BCCvL (which is not exposed in beta currently)

Developer time: ~5 days

**Comment by Tasilee** [comment]
After discussion with @adam-collins, there are a few hidden aspects. First is the need for a sprint with BCCvL to discuss how the trait 'columns' are exposed and passed over. This implies work on the BCCvL end. Second, this export (either to BCCvL or as Export | Points (with trait values and optionally environmental data intersect values) requires some biocache work. I have therefore upped the resourcing to 5 days developer time (ALA end only!).

**Comment by m-hope** [comment]
After the discussion with Adam this morning, I confirm that the immediate requirement for the EcoCloud project is to include trait information in the Export | Point downloads and that the Export | BCCVL functionality can come later.  However, there is also an additional assumption in that first component in that any list attribute/trait data that is uploaded to a layer as part of the "Add to Map | Species" process needs to be "transferred" or carried across to any layers derived from that original layer.  

This should mean that our deliverable to EcoCloud at the end of October will be a workflow that allows a user to:
-	Load occurrence records into the Spatial Portal (beta) using the “Add to Map->Species->Use Species List” option (either one of the sample trait lists or one they have created themselves) and have the values for any attributes/fields in the list(s) appended to each relevant occurrence record.
-	Manipulate or create new layers based on the trait/attribute data as facets and have the attribute/trait values carry across to the new layer.
-	Download the selected point layer and have the attribute/trait data included in each record in the download.  This download file can then be manually uploaded by the user into BCCVL for analysis.

At some point in the future, when a mutual time can be arranged with the BCCVL developers, the functionality of the current BCCVL Export will be changed to include any attribute/trait values if they are present in the selected layer. This will then change the workflow so that the Export | BCCVL function can replace the Export | Points process above.

**Comment by Tasilee** [comment]
Yes @m-hope, this was my feeling but I would also include the current ability to append environmental layer intersections at the points in the selected layer.
