### ISSUE TITLE
Links in Copy Layers from remote server interface are broken

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#116]
The `(L)` and `(R)` links in the "Copy Layers from remote server" interface are currently broken. I am not sure if it is a config and a software issue, but there are also slight differences between https://nectar-spatial-staging.ala.org.au/ws/manageLayers/remote and https://spatial-beta.ala.org.au/ws/manageLayers/remote .

Eg., when choosing "local and remote" on https://nectar-spatial-staging.ala.org.au/ws/manageLayers/remote 

The `L` link for the `cl3` field points to 

https://nectar-spatial-staging.ala.org.au/manageLayers/field/cl3

and the `R` link points to:

https://nectar-spatial-staging.ala.org.au/ws/manageLayers/field/cl3

The `L` link should point to 

https://nectar-spatial-staging.ala.org.au/ws/manageLayers/field/cl3

and the 'R' link should point to:

https://spatial-beta.ala.org.au/ws/manageLayers/field/cl3

The layer links are broken in a similar way.

The links are broken in a slightly different way on `spatial-beta`, with the `R` links appearing to be correct, and the `L` links broken. https://spatial-beta.ala.org.au/ws/manageLayers/remote

**Comment by adam-collins** [comment]
Layers and fields that are not enabled are incorrectly missing from "Copy Layers from remote server".

"Copy Layers from remote server" is a pull not a push. The intended usage is:
1. Load layer on to nectar-spatial-staging.
2. Use https://spatial-beta.ala.org.au/ws/manageLayers/remote to pull the loaded layer to spatial-beta.
3. Enable the new layers and fields on spatial-beta.

"Copy Layers from remote server" is unusable on staging because the default remote server is itself.

**Comment by ansell** [comment]
That sounds good. So just fixing the links on the spatial-beta interface, where only the `L` links are broken, would be enough to close this issue.
