### ISSUE TITLE
Double parse exception for empty string when creating layer

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#7]
When I am uploading a test dataset and creating a layer from it,

http://data.daff.gov.au/data/warehouse/9aaf/aif/2013/aif13g9abfs20131231egialb132.zip

there is an exception generated when it encounters an empty string and tries to parse it as a Double. 

<img width="1134" alt="screen shot 2016-05-30 at 3 47 25 pm" src="https://cloud.githubusercontent.com/assets/82365/15640690/0ace7188-267e-11e6-802e-490f62a23ff6.png">

The line in question is trying to parse maxlatitude, which seems to be a read-only parameter on the create layer page so I can't influence it directly.

<img width="1152" alt="screen shot 2016-05-30 at 3 49 40 pm" src="https://cloud.githubusercontent.com/assets/82365/15640722/573e0038-267e-11e6-9aab-f652676e3641.png">

**Comment by ansell** [comment]
The upload process needs to fail earlier than this in the case that unsupported upload formats are given to enable users to know they need to try different formats.

In the case here, the upload was an ARCGIS format, which I needed to convert to ESRI HDR format before uploading.

I ended up using the following commands to perform the conversion, which may be useful for others to use in future for similar cases:

```bash
$ unzip aif13g9abfs20131231egialb132.zip
$ gdal_translate -of EHdr aif13g9abfs20131231egialb132/ind_for13/ indigenous_forest_estate.bil
$ zip -r indigenous_forest_estate_processed.EHdr.zip indigenous_forest_estate.*
```

This issue is still open as the error should be highlighted much earlier in the process to reduce confusion.

**Comment by adam-collins** [comment]
It is low priority to inform administrators when the layer uploaded is not bil or shapefile. This is because it is written in the text on spatial-service/manageLayers/index

The file in this case, while being a raster, is actually a contextual layer file. This is determined by the Text lookup values in the source raster. Due to the complexity of the file it may exceed the 2GB shapefile size limit during conversion with gdal_polygonize.py. If it does not exceed the file size limit, the GDALRasterAttributeTable information needs to be added to the generated shapefile. GDALRasterAttributeTable info  can be viewed using gdalinfo on the source raster.

If it does exceed the file size limit it must be imported as a "grid file as contextual layer" which is not yet implemented in the new UI. The manual process will be similar to https://github.com/AtlasOfLivingAustralia/layer-ingestion/blob/master/contextual_load_GridClassBuilder.sh, with mode instead of cubespline in the warp, and a properties format .txt file (key=value) for the raster value to Text lookup CLASSES_MAPPING_FILE, and mapping to the new directory structure for the outputs. Might be best to wait for this to be implemented in the UI, however the  CLASSES_MAPPING_FILE will be required in the zip containing the bil file.

**Comment by ansell** [comment]
It would reduce stress levels for people using the service if it had error messages and indicated when they did something that was unsupported. That is far from being a "low priority" from my point of view.

Currently all of the error messages, from looking through the code, seem to be swallowed and only sent to a log file that the administrator can see but the user cannot see. This results in the workflow possibly passing points where it cannot work and should have failed early, and because it passed that point, it results in unrelated error reports such as this which waste both the maintainer and the users time. If the workflow emits proper exceptions and fails early it would enable me to submit more accurate error reports when things are broken.

I am not sure how to act on the things you referred to in your comment above as I have never worked with GIS before using this service so I will leave those steps to you.
